CREATE TABLE announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    body TEXT NOT NULL,
    audience VARCHAR(20) NOT NULL,
    state_id BIGINT REFERENCES states(id),
    published BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT REFERENCES members(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_announcements_audience ON announcements(audience);
CREATE INDEX idx_announcements_state ON announcements(state_id);
