ALTER TABLE events ADD COLUMN approved BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE events ADD COLUMN created_by BIGINT REFERENCES members(id);
ALTER TABLE promo_videos ADD COLUMN approved BOOLEAN NOT NULL DEFAULT TRUE;
