ALTER TABLE members DROP CONSTRAINT ck_member_role;
ALTER TABLE members ADD CONSTRAINT ck_member_role CHECK (role IN (
    'MEMBER', 'POLLING_UNIT_COORDINATOR', 'WARD_COORDINATOR', 'LGA_COORDINATOR',
    'COORDINATOR', 'ZONAL_COORDINATOR', 'GRAND_PATRON', 'MEDIA_COORDINATOR', 'ADMIN'
));
