-- GAT 2027 schema. Written in portable SQL so it runs on PostgreSQL (production) and H2 in PostgreSQL mode (local dev).

CREATE TABLE zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(8) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id BIGINT NOT NULL REFERENCES zones(id),
    code VARCHAR(4) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL UNIQUE,
    capital VARCHAR(64)
);

CREATE TABLE lgas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_id BIGINT NOT NULL REFERENCES states(id),
    code VARCHAR(4) NOT NULL,
    name VARCHAR(120) NOT NULL,
    CONSTRAINT uq_lga_state_name UNIQUE (state_id, name)
);
CREATE INDEX idx_lgas_state ON lgas(state_id);

CREATE TABLE wards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lga_id BIGINT NOT NULL REFERENCES lgas(id),
    code VARCHAR(20),
    name VARCHAR(160) NOT NULL,
    CONSTRAINT uq_ward_lga_name UNIQUE (lga_id, name)
);
CREATE INDEX idx_wards_lga ON wards(lga_id);

CREATE TABLE polling_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ward_id BIGINT NOT NULL REFERENCES wards(id),
    code VARCHAR(40),
    name VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_pu_ward_name UNIQUE (ward_id, name)
);
CREATE INDEX idx_pu_ward ON polling_units(ward_id);

CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_code VARCHAR(20) NOT NULL UNIQUE,
    referral_code VARCHAR(20) NOT NULL UNIQUE,
    referred_by BIGINT,
    role VARCHAR(16) NOT NULL DEFAULT 'MEMBER',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    first_name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80) NOT NULL,
    other_name VARCHAR(80),
    gender VARCHAR(8),
    dob DATE,
    phone VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(120),
    address VARCHAR(300),
    occupation VARCHAR(100),
    education VARCHAR(60),
    vin VARCHAR(30),
    photo TEXT,
    zone_id BIGINT REFERENCES zones(id),
    state_id BIGINT REFERENCES states(id),
    lga_id BIGINT REFERENCES lgas(id),
    ward_id BIGINT REFERENCES wards(id),
    polling_unit_id BIGINT REFERENCES polling_units(id),
    pu_latitude DOUBLE PRECISION,
    pu_longitude DOUBLE PRECISION,
    password_hash VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_member_role CHECK (role IN ('MEMBER', 'COORDINATOR', 'ADMIN')),
    CONSTRAINT ck_member_status CHECK (status IN ('ACTIVE', 'SUSPENDED')),
    CONSTRAINT ck_member_gender CHECK (gender IS NULL OR gender IN ('Male', 'Female'))
);
CREATE INDEX idx_members_referred_by ON members(referred_by);
CREATE INDEX idx_members_state ON members(state_id);
CREATE INDEX idx_members_lga ON members(lga_id);
CREATE INDEX idx_members_ward ON members(ward_id);
CREATE INDEX idx_members_pu ON members(polling_unit_id);
CREATE INDEX idx_members_created ON members(created_at);

CREATE TABLE field_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members(id),
    category VARCHAR(32) NOT NULL,
    title VARCHAR(160) NOT NULL,
    body TEXT NOT NULL,
    state_id BIGINT REFERENCES states(id),
    lga_id BIGINT REFERENCES lgas(id),
    ward_id BIGINT REFERENCES wards(id),
    polling_unit_id BIGINT REFERENCES polling_units(id),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    admin_note VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_report_category CHECK (category IN ('ACTIVITY', 'VOTER_MOBILISATION', 'INCIDENT', 'COMPLAINT', 'OTHER')),
    CONSTRAINT ck_report_status CHECK (status IN ('OPEN', 'REVIEWED', 'CLOSED'))
);
CREATE INDEX idx_reports_member ON field_reports(member_id);
CREATE INDEX idx_reports_status ON field_reports(status);

CREATE TABLE app_settings (
    setting_key VARCHAR(64) PRIMARY KEY,
    setting_value VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE persistent_logins (
    username VARCHAR(64) NOT NULL,
    series VARCHAR(64) PRIMARY KEY,
    token VARCHAR(64) NOT NULL,
    last_used TIMESTAMP NOT NULL
);
