CREATE TABLE event_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    image_data TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0
);
CREATE INDEX idx_event_photos_event ON event_photos(event_id);
